### ISSUE TITLE
Package import error: ipyvuetify

### ISSUE THREAD

**Issue by JohnMBrandt** [openforis/glad_alerts#2]
On a fresh VM, the UI notebook fails to run because ipyvuetify is not installed.

Either update the VM AMI or include this in the first cell

```python
%autoreload 2
import sys
!{sys.executable} -m pip install ipyvuetify==1.4.1
```

**Comment by 12rambau** [comment]
I prefer to leave it that way, the packages will all be installed when the module will be in production on SEPAL
